# Generated by Django 4.2.7 on 2023-12-15 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transferApp', '0003_application_remove_transferapplication_district_from_and_more'),
        ('officersApp', '0003_somemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dededucationofficertransfer',
            name='transfer_application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transferApp.application'),
        ),
    ]
