# Generated by Django 4.2.7 on 2023-12-22 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locationApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='registration',
            field=models.FloatField(blank=True, default=0, max_length=10, null=True),
        ),
    ]
