# Generated by Django 4.2.7 on 2023-12-22 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locationApp', '0002_school_registration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='registration',
            field=models.IntegerField(blank=True, default=1000, max_length=10, null=True),
        ),
    ]
