# Generated by Django 4.2.7 on 2023-11-21 20:48

import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locationApp', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('fname', models.CharField(max_length=100)),
                ('mname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=100)),
                ('birthdate', models.DateTimeField(null=True)),
                ('nin', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.MaxLengthValidator(limit_value=20), django.core.validators.MinLengthValidator(limit_value=20)])),
                ('image', models.ImageField(blank=True, max_length=255, null=True, upload_to='images/')),
                ('is_teacher', models.BooleanField(default=False)),
                ('is_education_officer', models.BooleanField(default=False)),
                ('is_ded', models.BooleanField(default=False)),
                ('is_tamisemi', models.BooleanField(default=False)),
                ('is_utumishi', models.BooleanField(default=False)),
                ('password', models.CharField(blank=True, max_length=180, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('retirement', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='EducationLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=110)),
            ],
        ),
        migrations.CreateModel(
            name='SalaryScale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scale', models.CharField(max_length=50, null=True)),
                ('amount', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('subjectcode', models.IntegerField(null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkerGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UtumishiUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='userApp.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='locationApp.district')),
                ('education_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userApp.educationlevel')),
                ('grade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userApp.workergrade')),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='locationApp.region')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='locationApp.school')),
                ('school_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locationApp.schoollevel')),
                ('subjects_taught', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userApp.subject')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='userApp.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='TamisemiUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='userApp.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='EducationOfficer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='locationApp.district')),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='locationApp.region')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='userApp.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='DistrictExecutiveDirector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='locationApp.district')),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='locationApp.region')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='userApp.customuser')),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='gender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userApp.gender'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(related_name='custom_user_groups', to='auth.group'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userApp.position'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(related_name='custom_user_permissions', to='auth.permission'),
        ),
    ]
