# Generated by Django 4.2.7 on 2023-11-30 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0002_kindofofficer'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationofficer',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userApp.kindofofficer'),
        ),
    ]
