# Generated by Django 4.2.7 on 2023-12-22 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0007_supervisor_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supervisor',
            name='level',
        ),
        migrations.RemoveField(
            model_name='supervisor',
            name='school',
        ),
    ]
