# Generated by Django 4.2.7 on 2023-12-24 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0008_remove_supervisor_level_remove_supervisor_school'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='subjects_taught',
        ),
        migrations.AddField(
            model_name='teacher',
            name='subjects_taught',
            field=models.ManyToManyField(blank=True, to='userApp.subject'),
        ),
    ]
