# Generated by Django 4.2.7 on 2023-11-28 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locationApp', '0001_initial'),
        ('userApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_date', models.DateTimeField(auto_now_add=True)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('district_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_application_district_from', to='locationApp.district')),
                ('district_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_application_district_to', to='locationApp.district')),
                ('region_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_application_region_from', to='locationApp.region')),
                ('region_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_application_region_to', to='locationApp.region')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userApp.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='UtumishiTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_date', models.DateTimeField(auto_now_add=True)),
                ('salary_transfer_complete', models.BooleanField(default=False)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='transferApp.transferapplication')),
                ('transferred_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userApp.utumishiuser')),
            ],
        ),
        migrations.CreateModel(
            name='TransferVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_date', models.DateTimeField(auto_now_add=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transferApp.transferapplication')),
                ('verified_ded', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userApp.districtexecutivedirector')),
                ('verified_officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userApp.educationofficer')),
            ],
        ),
        migrations.CreateModel(
            name='TransferSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='transferApp.transferapplication')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userApp.educationofficer')),
            ],
        ),
        migrations.CreateModel(
            name='TamisemiConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmation_date', models.DateTimeField(auto_now_add=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='transferApp.transferapplication')),
                ('confirmed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userApp.tamisemiuser')),
            ],
        ),
        migrations.CreateModel(
            name='SupportingDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='supporting_documents/')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transferApp.transferapplication')),
            ],
        ),
    ]
