# Generated by Django 4.2.7 on 2023-11-28 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transferApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferReasons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='transferapplication',
            name='reason',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='transferApp.transferreasons'),
        ),
    ]
