# Generated by Django 4.2.7 on 2023-12-15 13:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locationApp', '0001_initial'),
        ('userApp', '0005_teacher_course'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transferApp', '0002_transferreasons_transferapplication_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_type', models.CharField(choices=[('teacher', 'Teacher Application'), ('transfer', 'Transfer Application')], max_length=10)),
                ('reason', models.TextField()),
                ('supporting_document', models.FileField(upload_to='supporting_documents/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userApp.course')),
                ('district_from', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfer_application_district_from', to='locationApp.district')),
                ('district_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfer_application_district_to', to='locationApp.district')),
                ('education_level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userApp.educationlevel')),
                ('grade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userApp.workergrade')),
                ('region_from', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfer_application_region_from', to='locationApp.region')),
                ('region_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfer_application_region_to', to='locationApp.region')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='locationApp.school')),
                ('school_level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='locationApp.schoollevel')),
                ('subjects_taught', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userApp.subject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='transferapplication',
            name='district_from',
        ),
        migrations.RemoveField(
            model_name='transferapplication',
            name='district_to',
        ),
        migrations.RemoveField(
            model_name='transferapplication',
            name='reason',
        ),
        migrations.RemoveField(
            model_name='transferapplication',
            name='region_from',
        ),
        migrations.RemoveField(
            model_name='transferapplication',
            name='region_to',
        ),
        migrations.RemoveField(
            model_name='transferapplication',
            name='teacher',
        ),
        migrations.DeleteModel(
            name='SupportingDocument',
        ),
        migrations.AlterField(
            model_name='tamisemiconfirmation',
            name='application',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='transferApp.application'),
        ),
        migrations.AlterField(
            model_name='transfersubmission',
            name='application',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='transferApp.application'),
        ),
        migrations.AlterField(
            model_name='transferverification',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transferApp.application'),
        ),
        migrations.AlterField(
            model_name='utumishitransfer',
            name='application',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='transferApp.application'),
        ),
    ]
