# Generated by Django 4.2.7 on 2023-12-15 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transferApp', '0003_application_remove_transferapplication_district_from_and_more'),
        ('officersApp', '0004_alter_dededucationofficertransfer_transfer_application'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TransferApplication',
        ),
    ]
